# Generated by Django 2.2 on 2020-03-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Email of the person')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the person')),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Country of case')),
                ('source', models.CharField(blank=True, max_length=250, null=True, verbose_name='Source of case')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Information of case')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address of case')),
                ('info', models.CharField(blank=True, max_length=250, null=True, verbose_name='Information of case deaths, recoveries, critical or other')),
                ('date', models.DateField(verbose_name='Date of register')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Get Current date and time ')),
            ],
            options={
                'verbose_name': 'reportpeople',
                'verbose_name_plural': 'reportpeoples',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Get Current date and time ')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the volunteer')),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Country name of the volunteer')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='City name of the volunteer')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address name of the volunteer')),
                ('date', models.DateField(verbose_name='Date of register')),
            ],
            options={
                'verbose_name': 'volunteer',
                'verbose_name_plural': 'voulunteers',
            },
        ),
    ]
