# Generated by Django 2.2 on 2020-03-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_auto_20200321_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='info',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Information about youself'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='role',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Volunteer type'),
        ),
    ]
